apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common-api.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "common-api.fullname" . }}-tls
  privateKey:
    algorithm: {{ .Values.certificate.keyAlgorithm | default "RSA" }}
    size: {{ .Values.certificate.keySize | default 2048 }}
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: {{ .Values.certificate.issuerKind | default "ClusterIssuer" }}