apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-api.fullname" . }}
  labels:
    {{- include "common-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "common-api.fullname" . }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "common-api.fullname" . }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.namespace }}/{{ include "common-api.fullname" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}