{{- if and .Values.gateway (default false .Values.gateway.enabled) }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "common-api.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.route.host }}
    port:
      name: https
      number: 8443
      protocol: HTTPS
    tls:
      credentialName: {{ include "common-api.fullname" . }}-tls
      mode: {{ .Values.tls.mode }}
{{- end }}