replicaCount: 1

namespaceOverride: ""

containerPort: 8080
servicePort: 8080

image:
  tag: latest

serviceAccount:
  create: true

route:
  enabled: true
  host: ""

build:
  enabled: true
  git:
    uri: "https://github.com/glaceroy/smesh-api-backend.git"
    ref: main
    contextDir: ""
  dockerfilePath: Dockerfile
  sourceSecret: git-secret

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20